import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
      <Script
        src="https://use.fontawesome.com/e3ae05b8e6.js"
        strategy="beforeInteractive"
      />
    </head>
    <body className={inter.className}>{children}</body>
    </html>
  );
}
